sonar.projectKey=meethem-test
sonar.projectName=Meethem测试项目3
sonar.projectVersion=1.0
sonar.sources=E:\ruanjianceshi\meethere\SoftwareTesting-MeetHere-master\src\main
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqa_8ab06683b6cf474d686aabbf9e73d82f3226671b