#.yml=.yaml
#application.yml =application.properties(但是里面的格式不一样）

server:
  port: 8880
spring:
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML
    prefix: classpath:/templates/
    #classpath 是 Java 编译后的根目录。target/classes/
    suffix: .html
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    url: jdbc:mysql://localhost:3306/meethere_db?useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_To_NULL&serverTimezone=Asia/Shanghai
    username: root
    password: 200571
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
       ddl-auto: update
    database: mysql
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
